using System.Text.Json.Serialization;
using VeniceAI.SDK.Models.Common;

namespace VeniceAI.SDK.Models.Chat;

/// <summary>
/// Response from chat completion API.
/// </summary>
public class ChatCompletionResponse : BaseResponse
{
    /// <summary>
    /// Unique identifier for the chat completion.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// The object type, which is always "chat.completion".
    /// </summary>
    [JsonPropertyName("object")]
    public string Object { get; set; } = "chat.completion";

    /// <summary>
    /// The Unix timestamp (in seconds) of when the chat completion was created.
    /// </summary>
    [JsonPropertyName("created")]
    public long Created { get; set; }

    /// <summary>
    /// The model used for the chat completion.
    /// </summary>
    [JsonPropertyName("model")]
    public string Model { get; set; } = string.Empty;

    /// <summary>
    /// A list of chat completion choices.
    /// </summary>
    [JsonPropertyName("choices")]
    public List<ChatChoice> Choices { get; set; } = new();

    /// <summary>
    /// Usage statistics for the completion request.
    /// </summary>
    [JsonPropertyName("usage")]
    public Usage? Usage { get; set; }

    /// <summary>
    /// The system fingerprint, which represents the backend configuration.
    /// </summary>
    [JsonPropertyName("system_fingerprint")]
    public string? SystemFingerprint { get; set; }

    /// <summary>
    /// Citations for web search results (if web search was enabled).
    /// </summary>
    [JsonPropertyName("citations")]
    public List<Citation>? Citations { get; set; }
}

/// <summary>
/// A chat completion choice.
/// </summary>
public class ChatChoice
{
    /// <summary>
    /// The index of the choice in the list of choices.
    /// </summary>
    [JsonPropertyName("index")]
    public int Index { get; set; }

    /// <summary>
    /// A chat completion message generated by the model.
    /// </summary>
    [JsonPropertyName("message")]
    public AssistantMessage Message { get; set; } = new();

    /// <summary>
    /// Log probability information for the choice.
    /// </summary>
    [JsonPropertyName("logprobs")]
    public LogProbs? Logprobs { get; set; }

    /// <summary>
    /// The reason the model stopped generating tokens.
    /// </summary>
    [JsonPropertyName("finish_reason")]
    public string? FinishReason { get; set; }
}

/// <summary>
/// Usage statistics for the completion request.
/// </summary>
public class Usage
{
    /// <summary>
    /// Number of tokens in the prompt.
    /// </summary>
    [JsonPropertyName("prompt_tokens")]
    public int PromptTokens { get; set; }

    /// <summary>
    /// Number of tokens in the generated completion.
    /// </summary>
    [JsonPropertyName("completion_tokens")]
    public int CompletionTokens { get; set; }

    /// <summary>
    /// Total number of tokens used in the request (prompt + completion).
    /// </summary>
    [JsonPropertyName("total_tokens")]
    public int TotalTokens { get; set; }

    /// <summary>
    /// Breakdown of tokens used in the completion.
    /// </summary>
    [JsonPropertyName("completion_tokens_details")]
    public CompletionTokensDetails? CompletionTokensDetails { get; set; }
}

/// <summary>
/// Breakdown of tokens used in the completion.
/// </summary>
public class CompletionTokensDetails
{
    /// <summary>
    /// Number of reasoning tokens used.
    /// </summary>
    [JsonPropertyName("reasoning_tokens")]
    public int? ReasoningTokens { get; set; }
}

/// <summary>
/// Log probability information.
/// </summary>
public class LogProbs
{
    /// <summary>
    /// A list of message content tokens with log probability information.
    /// </summary>
    [JsonPropertyName("content")]
    public List<TokenLogProb>? Content { get; set; }
}

/// <summary>
/// Token log probability information.
/// </summary>
public class TokenLogProb
{
    /// <summary>
    /// The token.
    /// </summary>
    [JsonPropertyName("token")]
    public string Token { get; set; } = string.Empty;

    /// <summary>
    /// The log probability of this token.
    /// </summary>
    [JsonPropertyName("logprob")]
    public double Logprob { get; set; }

    /// <summary>
    /// A list of the most likely tokens and their log probabilities.
    /// </summary>
    [JsonPropertyName("top_logprobs")]
    public List<TopLogProb>? TopLogprobs { get; set; }
}

/// <summary>
/// Top log probability information.
/// </summary>
public class TopLogProb
{
    /// <summary>
    /// The token.
    /// </summary>
    [JsonPropertyName("token")]
    public string Token { get; set; } = string.Empty;

    /// <summary>
    /// The log probability of this token.
    /// </summary>
    [JsonPropertyName("logprob")]
    public double Logprob { get; set; }
}

/// <summary>
/// Citation information for web search results.
/// </summary>
public class Citation
{
    /// <summary>
    /// The citation ID.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// The title of the cited source.
    /// </summary>
    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// The URL of the cited source.
    /// </summary>
    [JsonPropertyName("url")]
    public string Url { get; set; } = string.Empty;

    /// <summary>
    /// Snippet of content from the cited source.
    /// </summary>
    [JsonPropertyName("snippet")]
    public string? Snippet { get; set; }
}
